### ISSUE TITLE
Errors when running the scripts

### ISSUE THREAD

**Issue by yangshuo11** [mveres01/multi-contact-grasping#7]
Many thanks! According to your suggestion, I try it and find it works out. Here is what I do to solve this problem:
Open the shell commend, and input: 
git clone https://github.com/mveres01/multi-contact-grasping
cd multi-contact-grasping
git checkout dev

Then I run the script src/collect_grasps.py. it works out correctly.

Thanks a lot. I will do grasp research based on it and make some progression in the future.

_Originally posted by @vanusy in https://github.com/mveres01/multi-contact-grasping/issues/5#issuecomment-382666458_

**Comment by yangshuo11** [comment]
Hello, I am using Ubuntu 16.04 + ROS kinetic, V-REP-3.6.1.
After installing trimesh-2.29.10, and cope relevant files from V-REP/programming to /lib. I encountered the following errors when running "python collect_grasps.py":
Traceback (most recent call last):
  File "collect_grasps.py", line 6, in <module>
    import trimesh
  File "/usr/local/lib/python2.7/dist-packages/trimesh/__init__.py", line 20, in <module>
    from .io.load import load_mesh, load_path, load, available_formats
  File "/usr/local/lib/python2.7/dist-packages/trimesh/io/load.py", line 14, in <module>
    from .assimp import _assimp_loaders
  File "/usr/local/lib/python2.7/dist-packages/trimesh/io/assimp.py", line 130, in <module>
    import pyassimp
  File "/usr/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 29, in <module>
    class AssimpLib(object):
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 33, in AssimpLib
    load, load_mem, release, dll = helper.search_library()
ValueError: need more than 3 values to unpack

and get the errors when running "python collect_images.py":
Traceback (most recent call last):
  File "collect_images.py", line 15, in <module>
    from postprocess import postprocess
  File "/home/ys/multi-contact-grasping/src/postprocess.py", line 9, in <module>
    from lib.utils import (format_htmatrix, invert_htmatrix,
  File "../lib/utils.py", line 5, in <module>
    import trimesh
  File "/usr/local/lib/python2.7/dist-packages/trimesh/__init__.py", line 20, in <module>
    from .io.load import load_mesh, load_path, load, available_formats
  File "/usr/local/lib/python2.7/dist-packages/trimesh/io/load.py", line 14, in <module>
    from .assimp import _assimp_loaders
  File "/usr/local/lib/python2.7/dist-packages/trimesh/io/assimp.py", line 130, in <module>
    import pyassimp
  File "/usr/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 29, in <module>
    class AssimpLib(object):
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 33, in AssimpLib
    load, load_mem, release, dll = helper.search_library()
ValueError: need more than 3 values to unpack

I have tried both the master and dev branches, but the errors remain the same. Could anyone give a clue? Many thanks!
